# steps:
#   - id: test-builds-successfully
#     name: bash
#     script: |
#       #!/usr/bin/env bash
#       cp -r . /workspace/
#       git branch -a

# steps:
# - name: 'gcr.io/cloud-builders/git'
#   entrypoint: /bin/bash
#   args:
#     - -c
#     - |
#         # Cloud Build doesn't recover the .git file. Thus checkout the repo for this
#         git clone --branch $main https://github.com/hoyindev/cloud-build-samples.git /tmp/ ;
#         # Copy only the .git file
#         mv tmp/.git .
#         git branch -a



steps:
# - name: 'ubuntu'
#   script: |
#     #!/usr/bin/env bash
#     echo "Hello $_USER"
    
# - name: gcr.io/cloud-builders/git
#   args: ['clone', 'https://github.com/hoyindev/cloud-build-samples.git', '/workspace']

# - name: gcr.io/cloud-builders/git
#   args: ['fetch', '--unshallow']

- name: gcr.io/cloud-builders/git
  args:
    - -c
    - |
        git fetch --unshallow
        git branch -a

