# steps:
#   - id: test-builds-successfully
#     name: bash
#     script: |
#       #!/usr/bin/env bash
#       cp -r . /workspace/
#       git branch -a

steps:
- name: 'gcr.io/cloud-builders/git'
  entrypoint: /bin/bash
  args:
    - -c
    - |
        # Cloud Build doesn't recover the .git file. Thus checkout the repo for this
        # git clone --branch $main https://github.com/hoyindev/cloud-build-samples.git / ;
        # Copy only the .git file
        # mv / .
        git branch -a

