# steps:
#   - id: test-builds-successfully
#     name: bash
#     script: |
#       #!/usr/bin/env bash
#       cp -r . /workspace/
#       git branch -a

# steps:
# - name: 'gcr.io/cloud-builders/git'
#   entrypoint: /bin/bash
#   args:
#     - -c
#     - |
#         # Cloud Build doesn't recover the .git file. Thus checkout the repo for this
#         git clone --branch $main https://github.com/hoyindev/cloud-build-samples.git /tmp/ ;
#         # Copy only the .git file
#         mv tmp/.git .
#         git branch -a



# steps:
# # - name: 'ubuntu'
# #   script: |
# #     #!/usr/bin/env bash
# #     echo "Hello $_USER"
    
# # - name: gcr.io/cloud-builders/git
# #   args: ['clone', 'https://github.com/hoyindev/cloud-build-samples.git', '/workspace']

# # - name: gcr.io/cloud-builders/git
# #   args: ['fetch', '--unshallow']

# - name: gcr.io/cloud-builders/git
#   entrypoint: /bin/bash
#   args:
#     - -c
#     - |
#         git fetch --unshallow
#         git branch -a
# - name: 'bash'
#   script: |
#     #!/usr/bin/env bash
#     echo "Hello World"
#     git branch -a

#

steps:

- name: gcr.io/cloud-builders/git
  id: unshallow
  entrypoint: /bin/bash
  args:
    - -c
    - |
        git fetch 
        echo "fetch unshallow done"
        git branch -a
        echo "branch"
        echo "git tag"
        echo $(git tag)
        tag1=$(git tag --sort=-creatordate | head -n 1)
        tag2=$(git tag --sort=-creatordate | head -n 2 | tail -n 1)
        files=$(git diff $tag1 $tag2 --name-only)
        diff=$(git diff $tag1 $tag2)
        echo $diff
        echo "git tag"
        echo $(git tag)
        echo "test done"


- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  id: test
  entrypoint: 'bash'
  args:
    - -c
    - |
      git config http.sslVerify false
      echo "config"
      git fetch
      echo "fetch"
      tag1=$(git tag --sort=-creatordate | head -n 1)
      tag2=$(git tag --sort=-creatordate | head -n 2 | tail -n 1)
      files=$(git diff $tag1 $tag2 --name-only)
      diff=$(git diff $tag1 $tag2)
      echo $diff
      echo "git tag"
      echo $(git tag)
      echo "test done"